#include "GDT.h"

STATIC
GDT  g_GDT = {
    .Null       = GDT_NULL64,
    .KernelCode = GDT_SEGMENT64 (0x0000000000000000,0xFFFFF,  GDT_ACCESS_PRESENT | GDT_ACCESS_SYSTEM | GDT_ACCESS_PRIVILEGE0 | GDT_ACCESS_EXECUTABLE | GDT_ACCESS_READWRITE, GDT_GRANULARITY_4KB | GDT_GRANULARITY_64BIT),
    .KernelData = GDT_SEGMENT64 (0x0000000000000000,0xFFFFF,  GDT_ACCESS_PRESENT | GDT_ACCESS_SYSTEM | GDT_ACCESS_PRIVILEGE0 | GDT_ACCESS_READWRITE | GDT_ACCESS_DIRECTION,  GDT_GRANULARITY_4KB | GDT_GRANULARITY_64BIT),
    .UserCode   = GDT_SEGMENT64 (0x0000000000000000, 0xFFFFF, GDT_ACCESS_PRESENT | GDT_ACCESS_SYSTEM | GDT_ACCESS_PRIVILEGE3 | GDT_ACCESS_EXECUTABLE | GDT_ACCESS_READWRITE, GDT_GRANULARITY_4KB | GDT_GRANULARITY_64BIT),
    .UserData   = GDT_SEGMENT64 (0x0000000000000000, 0xFFFFF, GDT_ACCESS_PRESENT | GDT_ACCESS_SYSTEM | GDT_ACCESS_PRIVILEGE3 | GDT_ACCESS_READWRITE | GDT_ACCESS_DIRECTION,  GDT_GRANULARITY_4KB | GDT_GRANULARITY_64BIT),
    .TSS        = GDT_NULL64,
};

STATIC
GDTR g_GDTR = {
    .Limit = sizeof (GDT) - 1,
    .Base  = (UINTN)&g_GDT,
};

/**
 * Initialize the GDT
 **/
VOID
SYSAPI
GDTInit (
    VOID
    )
{
    GDTLoad (&g_GDTR);

    GDTReloadSegments (GDT_KERNEL_CS, GDT_KERNEL_DS);
}
