#pragma once

// 00000000 00000000 00000000 00000000
// ^---------------------------------- Severity level
//  ^--------------------------------- User defined
//   ^^^^^^-^^^^^^^^------------------ Facility
//                   ^^^^^^^^-^^^^^^^^ Error code

#define STATUS_SEVERITY_ERROR_MASK     0x80000000
#define STATUS_USERDEFINED_MASK        0x40000000
#define STATUS_FACILITY_MASK           0x3FFF0000
#define STATUS_ERROR_CODE_MASK         0x0000FFFF

#define COMBINE_STATUS(Severity, UserDefined, Facility, ErrorCode) \
    ((((int)Severity) << 31) | (((int)UserDefined) << 30) | (((int)Facility) << 16) | ((int)ErrorCode))

#define STATUS_SEVERITY_SUCCESS        0
#define STATUS_SEVERITY_ERROR          1

#define STATUS_FACILITY_COMMON         0x0 // Common status codes.
#define STATUS_FACILITY_RESERVED_BEGIN 0x1 // reserved for now.
#define STATUS_FACILITY_RESERVED_END   0xF

/**
 * Common status codes.
 */
#define STATUS_SUCCESS                 COMBINE_STATUS(STATUS_SEVERITY_SUCCESS, 0,   STATUS_FACILITY_COMMON,  0)
#define STATUS_FAILURE                 COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON,  1)
#define STATUS_NOT_FOUND               COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON,  2)
#define STATUS_NOT_IMPLEMENTED         COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON,  3)
#define STATUS_NOT_SUPPORTED           COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON,  4)
#define STATUS_INVALID_HANDLE          COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON,  5)
#define STATUS_ACCESS_DENIED           COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON,  6)
#define STATUS_OUT_OF_MEMORY           COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON,  7)
#define STATUS_OUT_OF_RESOURCES        COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON,  8)
#define STATUS_OUT_OF_BOUNDS           COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON,  9)
#define STATUS_INVALID_PARAMETER       COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 10)
#define STATUS_TIMEOUT                 COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 11)
#define STATUS_ALREADY_EXISTS          COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 12)
#define STATUS_BUFFER_TOO_SMALL        COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 13)
#define STATUS_NOT_READY               COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 14)
#define STATUS_NOT_STARTED             COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 15)
#define STATUS_ALREADY_STARTED         COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 16)
#define STATUS_PENDING                 COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 17)
#define STATUS_CANCELLED               COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 18)
#define STATUS_UNALIGNED               COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 19)
#define STATUS_ALREADY_INITIALIZED     COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 20)
#define STATUS_NOT_INITIALIZED         COMBINE_STATUS(STATUS_SEVERITY_ERROR,   0,   STATUS_FACILITY_COMMON, 21)

#define SUCCESS(Status) ((Status & STATUS_SEVERITY_ERROR_MASK) == STATUS_SEVERITY_SUCCESS)
#define ERROR(Status)   ((Status & STATUS_SEVERITY_ERROR_MASK) == STATUS_SEVERITY_ERROR)
